### ISSUE TITLE
order of events in a month is reversed

### ISSUE THREAD

**Issue by willkg** [rtucker-mozilla/WhistlePig#52] opened 2014-10-07 01:08 UTC
I think you want this to read like a blog where the most recent event is at the top and it proceeds backwards in time as you read down the page.

Right now, the dates on events on the page are in this order:
- 2014-10-02
- 2014-10-03
- 2014-10-03
- 2014-10-03
- 2014-10-06
- 2014-09-02
- 2014-09-08
- 2014-09-10
- ...

Thus the most recent month is towards the top and months proceed backwards in time--that's fine.
However in a given month, the days are reversed.

Thus if you go to the status page now, you see 2014-10-02 stuff and have to scroll down, but not too far down, to see today's issues.

**Comment by rtucker-mozilla** [comment] 2014-10-07 11:56
This is a dupe of Issue #55 which we've tracked using bugzilla. I've copied the final verdict from bugzilla into Issue #55. Thanks.

**Closed as completed by rtucker-mozilla** 2014-10-07 11:56 UTC
